/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 model/scene.gltf 
Author: SKEIRON (https://sketchfab.com/skeiron)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/avrora-b7739e1f499541f0b65d398e3ee47f7f
Title: Avrora
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.tex_u1_v1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.tex_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
